name: Google keep CI/CD pipeline
on:
  push:
    branches:
      - main 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: 18

      -  name: Install Dependencies
         run: npm install

      - name: Build React App
        run: npm run build
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.ramneeshmaurya}}
          password: ${{ secrets.Ramneesh@2}}
        
      - name: Build Docker Image
        run: docker build -t ramneeshmaurya/google-keep-app:latest .

      - name: Push Docker Image
        run: docker push ramneeshmaurya/google-keep-app:latest
          
          